from setuptools import setup

setup(name='sls',
      version='0.1.0',
      description='Stochastic Line Search',
      url='git@github.com:IssamLaradji/sls.git',
      maintainer='Issam Laradji',
      maintainer_email='issam.laradji@gmail.com',
      license='MIT',
      packages=['sls'],
      zip_safe=False,
      install_requires=[
        'tqdm>=0.0',
        'numpy>=0.0',
        'pandas>=0.0',
        'Pillow>=0.0',
        'scikit-image>=0.0',
        'scikit-learn>=0.0',
        'scipy>=0.0',
        'scikit-learn>=0.0',
        'torch>=0.0',
        'torchvision>=0.0',
      ]),
